# Start from a Debian image with the latest version of Go installed
# and a workspace (GOPATH) configured at /go.
FROM golang

# Contact maintainer with any issues you encounter
MAINTAINER Saran Ahluwalia <ahlusar.ahluwalia@gmail.com>

# Set environment variables
ENV PATH /go/bin:$PATH

# Cd into the source code directory
WORKDIR /go/src/github.com/ahlusar1989/scheduling_service

# Copy the local package files to the container's workspace.
ADD . /go/src/github.com/ahlusar1989/scheduling_service

# Run integration tests as default command
CMD make test-with-coverage
